server:
  port: 8001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka
spring:
  datasource:
    url: jdbc:mysql://212.129.237.80:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: gd981010
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4


mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.situation.entity

