spring:
  application:
    name: eureka-server

server:
  port: 7001  #默认eureka-server是8761


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # server 不用将自己注册到eureka
    fetch-registry: false # server 也不需要从eureka中拉取服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka